- name: Include roles
  hosts: hdz
  vars_files:
    - group_vars/hdz.yml

  tasks:
    - name: Include SOPS secrets
      community.sops.load_vars:
        file: secrets.sops.enc.yml
        name: sops

    # This will need to become a separate playbook later.
    # The rest of these roles should be run as an ansible user anyway.
    - name: Create the automation user
      vars:
        bootstrap_user_name: "{{ automation_user }}"
        bootstrap_user_pswd_hash: "{{ sops.auth.automation_user_pswd_hash }}"
        bootstrap_user_groups: "{{ automation_groups }}"
      ansible.builtin.include_role:
        name: bootstrap_user
        tasks_from: main

    - name: Install docker
      ansible.builtin.include_role:
        name: install_docker
        tasks_from: main

    - name: Deploy reverse proxy
      vars:
        reverse_proxy_caddy_bouncer_key: "{{ sops.rproxy.caddy_cs_bouncer_token }}"
      ansible.builtin.include_role:
        name: reverse_proxy
        tasks_from: main

    - name: Deploy Vaultwarden
      ansible.builtin.include_role:
        name: vaultwarden
        tasks_from: main
