- name: Include roles
  hosts: hdz
  vars_files:
    - group_vars/hdz.yml

  tasks:
    - name: Include SOPS secrets
      community.sops.load_vars:
        file: secrets.sops.enc.yml
        name: sops

    # This will need to become a separate playbook later.
    # The rest of these roles should be run as an ansible user anyway.
    - name: Create the automation user
      vars:
        bootstrap_user_name: "{{ automation_user }}"
        bootstrap_user_pswd_hash: "{{ sops.auth.automation_user_pswd_hash }}"
        bootstrap_user_groups: "{{ automation_groups }}"
      ansible.builtin.include_role:
        name: bootstrap_user
        tasks_from: main

    - name: Configure iptables firewall
      ansible.builtin.include_role:
        name: firewall
        tasks_from: main

    - name: Install docker
      ansible.builtin.include_role:
        name: install_docker
        tasks_from: main

    - name: Deploy Vaultwarden
      ansible.builtin.include_role:
        name: vaultwarden
        tasks_from: main

    - name: Deploy soju bouncer
      ansible.builtin.include_role:
        name: soju
        tasks_from: main

    - name: Deploy NGINX reverse proxy
      ansible.builtin.include_role:
        name: nginx_reverse_proxy
        tasks_from: main

    - name: Install backup script
      vars:
        restic_repo_password: "{{ sops.restic.restic_repo_password }}"
        restic_repo_path: "{{ sops.restic.restic_repo_path }}"
        restic_hostname: "HDZ_main"
        restic_s3_key_id: "{{ sops.restic.r2_token_id }}"
        restic_s3_access_key: "{{ sops.restic.r2_token_secret }}"
      ansible.builtin.include_role:
        name: cron-backup
        tasks_from: main
