# - name: Run bootstrap_user if user does not exist
#   hosts: smalldog
#   vars:
#     ansible_ssh_user: root
#   tasks:
#     - name: "Check if user {{ user }} exists"
#       command: >
#         ssh -q -o BatchMode=yes -o ConnectTimeout=3 {{ user }}@{{ inventory_hostname }} "echo OK"
#       delegate_to: 127.0.0.1
#       changed_when: false
#       failed_when: false
#       register: check_ansible_user
#
#     - name: Bootstrap
#       ansible.builtin.include_role:
#         name: bootstrap_user
#       when: check_ansible_user.rc != 0

- name: Include roles
  hosts: hdz
  vars_files:
    - group_vars/hdz.yml

  tasks:
    - name: Include SOPS secrets
      community.sops.load_vars:
        file: secrets.sops.enc.yml
        name: sops

    - name: Create the automation user
      vars:
        user: "{{ automation_user }}"
        user_pswd_hash: "{{ sops.auth.automation_user_pswd_hash }}"
        user_groups: "{{ automation_groups }}"
      ansible.builtin.include_role:
        name: bootstrap_user
        tasks_from: main
