argument_specs:
  main:
    options:
      docker_dir:
        type: str
        required: true
        description: path to the docker container directory
      domain:
        type: str
        required: true
        description: the FQDN domain name (example.com)
      nginx_cf_dns_api_token:
        type: str
        required: true
        description: account API token with DNS edit permissions
      nginx_cf_account_id:
        type: str
        required: true
        description: account ID of the cloudflare account
