- name: Ensure restic and sqlite3
  ansible.builtin.apt:
    pkg:
      - sqlite3
      - restic
      - unzip
    state: present

- name: Output backup script
  ansible.builtin.template:
    src: backup_script.j2
    dest: "{{ ansible_env.HOME }}/backup.sh"
    mode: "0700"
