- name: Ensure packages
  ansible.builtin.apt:
    pkg:
      - sqlite3
      - restic
      - unzip
    state: present

- name: Set backup script directory variable
  ansible.builtin.set_fact:
    restic_backup_dir: "{{ ansible_env.HOME }}"

- name: Output env file
  ansible.builtin.template:
    src: restic.env.j2
    dest: "{{ restic_backup_dir }}/restic.env"
    mode: "0600"

- name: Output backup script
  ansible.builtin.template:
    src: backup_script.j2
    dest: "{{ restic_backup_dir }}/backup.sh"
    mode: "0700"

- name: Output restore script
  ansible.builtin.template:
    src: restore_script.j2
    dest: "{{ restic_backup_dir }}/restore.sh"
    mode: "0700"

- name: Creates a cron file under /etc/cron.d
  ansible.builtin.cron:
    name: restic backup
    day: "*"
    minute: "0"
    hour: "1"
    user: root
    job: "root {{ ansible_env.HOME }}/backup.sh"
    cron_file: ansible_restic_backup
