- name: Uninstall conflicting
  ansible.builtin.apt:
    state: absent
    pkg:
      - docker.io
      - docker-doc
      - podman-docker
      - docker-compose
      - containerd
      - runc

- name: Apt update cache and install packages
  ansible.builtin.apt:
    update_cache: true
    state: present
    pkg:
      - ca-certificates
      - curl
      - gnupg

- name: Set keyring dir perms
  ansible.builtin.file:
    path: /etc/apt/keyrings
    mode: '0755'

- name: Download docker gpg key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: a+r

- name: Get architecture
  ansible.builtin.set_fact:
    install_docker_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Put line in docker.list file
  ansible.builtin.lineinfile:
    create: true
    mode: "0644"
    line: >-
      deb [arch={{ install_docker_arch }} signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    path: /etc/apt/sources.list.d/docker.list

- name: Install docker
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

# POST INSTALL

- name: Make docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: "Add user to docker group"
  ansible.builtin.user:
    name: "{{ user }}"
    append: true
    groups: docker

- name: Start docker on startup
  ansible.builtin.systemd_service:
    name: docker.service
    enabled: true

- name: Start containerd on startup
  ansible.builtin.systemd_service:
    name: containerd.service
    enabled: true
