argument_specs:
  main:
    options:
      caddy_reverse_proxy_bouncer_key:
        type: str
        required: true
        description: bouncer API key to set for crowdsec <-> caddy interaction
      docker_dir:
        type: str
        required: true
        description: path to the docker container directory
      domain:
        type: str
        required: true
        description: the FQDN domain name (example.com)
