---
- name: Make the user {{ role_name }}
  ansible.builtin.user:
    name: "{{ role_name }}"
    uid: "{{ soju_uid }}"
    create_home: false
    shell: /usr/sbin/nologin

- name: Make the group {{ role_name }}
  ansible.builtin.group:
    name: "{{ role_name }}"
    state: present
    gid: "{{ soju_gid }}"

- name: Ensure directory is created
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ role_name }}"
    state: directory
    mode: "0700"
    owner: "{{ soju_uid }}"
    group: "{{ soju_gid }}"

- name: Ensure data directory is created
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ role_name }}/data"
    state: directory
    mode: "0700"
    owner: "{{ soju_uid }}"
    group: "{{ soju_gid }}"

- name: Ensure socket directory is created
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ role_name }}/sock"
    state: directory
    mode: "0700"
    owner: "{{ soju_uid }}"
    group: "{{ soju_gid }}"

- name: Output Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ docker_dir }}/{{ role_name }}/Dockerfile"
    mode: "0700"
    owner: "{{ soju_uid }}"
    group: "{{ soju_gid }}"
  notify:
    - Rebuild soju image

- name: Output compose.yml
  ansible.builtin.template:
    src: compose.j2
    dest: "{{ docker_dir }}/{{ role_name }}/compose.yml"
    mode: "0700"
    owner: "{{ soju_uid }}"
    group: "{{ soju_gid }}"
  notify:
    - Restart soju

- name: Output soju config file
  ansible.builtin.template:
    src: soju-config.j2
    dest: "{{ docker_dir }}/{{ role_name }}/soju-config"
    mode: "0700"
    owner: "{{ soju_uid }}"
    group: "{{ soju_gid }}"
  notify:
    - Restart soju

- name: Start docker container
  community.docker.docker_compose_v2:
    project_src: "{{ docker_dir }}/{{ role_name }}"

- name: Wait for container to be running
  community.docker.docker_container_info:
    name: "{{ role_name }}"
  register: soju_container_info
  retries: 10
  delay: 2
  until: soju_container_info.container.State.Running

- name: Wait for soju admin socket to be ready
  community.docker.docker_container_exec:
    container: "{{ role_name }}"
    command: "test -S /run/soju/soju-admin.sock"
  changed_when: false
  register: soju_socket_check
  retries: 15
  delay: 2
  until: soju_socket_check.rc == 0

- name: Make soju user
  community.docker.docker_container_exec:
    container: "{{ role_name }}"
    command: "sojuctl user create -username {{ soju_user }} -password {{ soju_password }} -admin -nick {{ soju_user }} -realname {{ soju_user }} -enabled"
  register: soju_user_make
  failed_when: false
  changed_when: "'already exists' not in (soju_user_make.stdout + soju_user_make.stderr)"

- name: Flush role handlers now
  ansible.builtin.meta: flush_handlers

- name: Run commands and waits sequentially
  ansible.builtin.include_tasks: soju_step.yml
  loop: "{{ soju_commands }}"
  loop_control:
    loop_var: step
