- name: Ensure directory is created
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ role_name }}"
    state: directory
    mode: "0740"

- name: Output Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ docker_dir }}/{{ role_name }}/Caddyfile"
    mode: "0740"
  notify:
    - Restart caddy

- name: Output compose file
  ansible.builtin.template:
    src: compose.j2
    dest: "{{ docker_dir }}/{{ role_name }}/compose.yml"
    mode: "0740"
  notify:
    - Restart caddy
    - Restart crowdsec

- name: Output Dockerfile
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ docker_dir }}/{{ role_name }}/Dockerfile"
    mode: "0740"
  notify:
    - Restart caddy
    - Restart crowdsec

- name: Make directory for acquis template
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ role_name }}/crowdsec/config/acquis.d/"
    state: directory
    mode: "0740"

- name: Output acquis.d file for caddy bouncer
  ansible.builtin.template:
    src: caddy_acquis.j2
    dest: "{{ docker_dir }}/{{ role_name }}/crowdsec/config/acquis.d/caddy.yaml"
    mode: "0740"

- name: Output acquis.d file for gitea collection
  ansible.builtin.template:
    src: gitea_acquis.j2
    dest: "{{ docker_dir }}/{{ role_name }}/crowdsec/config/acquis.d/gitea.yaml"
    mode: "0740"

- name: Output acquis.d file for vaultwarden collection
  ansible.builtin.template:
    src: vaultwarden_acquis.j2
    dest: "{{ docker_dir }}/{{ role_name }}/crowdsec/config/acquis.d/vaultwarden.yaml"
    mode: "0740"

- name: Create caddy_reverse_proxy network
  community.docker.docker_network:
    name: caddy_reverse_proxy

- name: Start docker container
  community.docker.docker_compose_v2:
    project_src: "{{ docker_dir }}/{{ role_name }}"

- name: Make bouncer api key in crowdsec
  community.docker.docker_container_exec:
    container: crowdsec
    command: cscli bouncer add caddy --key {{ caddy_reverse_proxy_bouncer_key }}
  register: caddy_reverse_proxy_bouncer_resp
  failed_when: "caddy_reverse_proxy_bouncer_resp.rc != 0 and 'already exists' not in caddy_reverse_proxy_bouncer_resp.stderr"
  changed_when: "'already exists' not in caddy_reverse_proxy_bouncer_resp.stderr"
  notify:
    - Restart caddy
    - Restart crowdsec
